#!/usr/bin/env python3

from subprocess import Popen
from time import sleep

try:
    with open('/var/run/gsm.pid') as f:
        pid = str(int(f.readline()))

except:
    exit(0)

else:
    proc = Popen(['kill', '-SIGTERM', pid])
    proc.wait()




